#!/usr/bin/env ruby
require File.expand_path('../../commons', __FILE__)
here = File.dirname(__FILE__)
lib = File.join(here, 'lib')
options = %q{--coffee --no-coffee-compile --libname=embedded-coffee}
output = File.join(here, 'embedded-coffee.coffee')
nibjs(options, __output(output), lib)