#!/usr/bin/env ruby
require File.expand_path('../../commons', __FILE__)
here = File.dirname(__FILE__)
lib = File.join(here, 'lib')
options = %q{--coffee --libname=coffee}
output = File.join(here, 'coffee.js')
nibjs(options, __output(output), lib)